### PR TITLE
Tidyup

### PR DESCRIPTION
**Pull request by julianpistorius**
**Beware!** - This pull request might delete files in your PyCharm `.idea` folder. Do the following steps:

- Close PyCharm
- Backup your `.idea` folder: `cp -R .idea ../idea_folder_backup`
- Pull the changes: `git pull`
- Restore backup: `cp -R ../idea_folder_backup/ .idea/`
- Open PyCharm

Other changes:
- Added another way of calculating number. Don't think it's meaningfully different.
- Added `requirements.txt` and `requirements.in` files. This makes it possible to...
- Launch the notebook directly from GitHub into [Binder](https://mybinder.org/). If you want to test how this works before merging the PR - try clicking on this button:  [Binder](https://mybinder.org/v2/gh/julianpistorius/random_plotting/tidyup?filepath=prior_testing.ipynb)

### CODE REVIEW

**Comment by julianpistorius** [comment]
Note: I'm using a Python 3 interpreter, as does the Binder environment.

**Comment by agladstein** [comment]
Can you can you commit from the binder or just edit and run?

**Comment by julianpistorius** [comment]
@agladstein Good question. I haven't tried committing from Binder. I think it might be possible if you can open a console, or a Bash cell. I wouldn't advise this though. It's risky from a security perspective - way too easy to mess up and leave your GitHub credentials on a publicly accessible server.

The way to do it securely and (relatively) simply is:

- Generate a patch file on Binder (via a console or Bash cell)
- Copy that patch to your local machine
- Apply it
- Commit and push changes

I might test this out.

**Comment by julianpistorius** [comment]
@agladstein Update: Yes, this is possible. You have a full terminal available. I was able to make a patch and download it. I could also do `git commit` and `git push` if I wanted - but I don't like typing my password into random Jupyter notebooks on the internet. :) If you are going to do that then definitely destroy the running terminal as soon as possible afterwards.

**Pull request merged**
